### ISSUE TITLE
Could you provide the pre-trained model parameters

### ISSUE THREAD

**Issue by solanoon** [jonghyunlee1993/DLM-DTI_hint-based-learning#2]
Hello,

I wonder whether could we get the pre-trained model parameters on the merged dataset for testing?

**Comment by jonghyunlee1993** [comment]
Unfortunately, I deleted the checkpoints of this projects for conducting another project. However, I think you can train the model relatively easily, as it does not require heavy computational resources. In my experience, each epoch takes 10 to 15 minutes. Sorry for the inconvenience.
